# Generated by Django 4.2 on 2024-02-20 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_table'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='products',
            new_name='cart_items',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_product', to='products.product', unique=True),
        ),
        migrations.AlterModelTable(
            name='cart',
            table='carts',
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='cart_items',
        ),
    ]
