# Generated by Django 4.2 on 2024-02-20 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_initial_quantity_alter_product_price'),
        ('carts', '0002_rename_products_cart_cart_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_product', to='products.product'),
        ),
    ]
