# Generated by Django 4.2 on 2024-02-22 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name',)},
        ),
    ]
