# Generated by Django 4.2 on 2024-03-08 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_rename_user_order_customer_alter_order_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='orderID',
        ),
    ]
