# Generated by Django 4.2 on 2024-02-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='initial_quantity',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
