# Generated by Django 4.2 on 2024-02-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_initial_quantity_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='initial_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
